FakeUnicodeImporter: XXX
Poc unloading the modules. Will be rejected cause:

- does not work for standalone - I don't really know why we exclude the
standalone from using our importer but then we do
- it's too fragile.

What I will do instead is just go ahead and delete the modules by hand
from game

filter(lambda obj: isinstance(obj, types.ModuleType)
                   and 'bash' in obj.__name__,
       gc.get_objects())

This was needed
@@ -61,2 +62,4 @@ def _supportedGames(useCache, fake_importer):
         fake_importer.cleanup()
+        del sys.modules['bash'].game
+        del sys.modules['bash'].brec
         sys.meta_path = [importer]

sys.modules['bash'] is the top Bash package that kept references to
game that kept references to all its submodules and brec that was
imported in game/oblivion _anew_ resulting in:

Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 118, in <module>
    bash.main(opts, FakeUnicodeImporter)
  File "bash\bash.py", line 389, in main
    _showErrorInGui(e, _wx=wx, bolt=bolt)
  File "bash\bash.py", line 385, in main
    import basher
  File "Wrye Bash Launcher.pyw", line 83, in load_module
    exec compile(code, initfile, 'exec') in mod.__dict__
  File "bash\basher\__init__.py", line 4093, in <module>
    from .gui_patchers import initPatchers
  File "Wrye Bash Launcher.pyw", line 70, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\basher\gui_patchers.py", line 920, in <module>
    from ..patcher.patchers import multitweak_actors, multitweak_assorted, \
  File "Wrye Bash Launcher.pyw", line 70, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\patcher\patchers\multitweak_assorted.py", line 2116, in <module>
    class AssortedTweaker(MultiTweaker):
  File "bash\patcher\patchers\multitweak_assorted.py", line 2147, in AssortedTweaker
    AssortedTweak_NoLightFlicker(),
  File "bash\patcher\patchers\multitweak_assorted.py", line 732, in __init__
    self.flags = flags = MreRecord.type_class['LIGH']._flags()
ImportError: caused by ImportError(u'caused by ImportError(u\'caused by TypeError("\\\'NoneType\\\' object has no attribute \\\'__getitem__\\\'",)\',)',)

cause basically the bash.brec was used while in oblivion.__init__#init()
MreRecord.type_class was updated for the brec there !!!

DUH

See http://stackoverflow.com/a/43700205/281545 for a detailed analysis

Under imports
Under game support