Regression - create new mod would crash due to mtime being None:
Traceback (most recent call last):
  File "bash\balt.py", line 2490, in __Execute
    self.Execute()
  File "bash\basher\mods_links.py", line 220, in Execute
    self.window.GetSelected())
  File "bash\bosh\__init__.py", line 2453, in generateNextBashedPatch
    masterless=True, bashed_patch=True)
  File "bash\bosh\__init__.py", line 2436, in create_new_mod
    newFile.safeSave()
  File "bash\parsers.py", line 4056, in safeSave
    filePath.temp.mtime = self.fileInfo.mtime
  File "bash\bolt.py", line 825, in _setmtime
    os.utime(self._s, (self.atime, int(mtime)))
TypeError: int() argument must be a string or a number, not 'NoneType'

This would crash Bash on start on generateNewBashedPatch, which was the
Nth crash due to that bright idea - who knows how many people tried to
install Bash and failed and never looked back due to this - creating a
file, especially with Bash's cryptic API's (like 'safeSave') is bound
to blow at one time or other, so you just don't do that on startup.
Monkey patched with `except:`.

Quite probably introduced in 2c034eda5b6648ca35ffba767af4a95618cfc922
where unset mtime changed to None from 0 - now I see why (as reported
by a puzzled user) bashed patch had a date of 1/1/1970 - so this fixes
that too.

Signed-off-by: MrD <the.ubik@gmail.com>